/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_evol_RPGNativeBridge */

#ifndef _Included_org_evol_RPGNativeBridge
#define _Included_org_evol_RPGNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_evol_RPGNativeBridge
 * Method:    evaluatePopulation
 * Signature: ([II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_evol_RPGNativeBridge_evaluatePopulation
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
