/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_evol_Poc */

#ifndef _Included_org_evol_Poc
#define _Included_org_evol_Poc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_evol_Poc
 * Method:    nativeLoop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_evol_Poc_nativeLoop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
